# Generated by Django 5.2.4 on 2025-07-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroP', '0002_produto_descriçao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descriçao',
            new_name='descricao',
        ),
    ]
